/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hasar_takip_sistemi_odev_final;

import java.sql.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author veliakdeniz
 */
public class AnaEkran extends javax.swing.JFrame {
    
    Date d = new Date(System.currentTimeMillis());
    
    public AnaEkran() {
        initComponents();
        DefaultComboBoxModel dlm = new DefaultComboBoxModel();
        dlm.addElement(new Araba().getAracTur());
        dlm.addElement(new Kamyon().getAracTur());
        dlm.addElement(new Motorsiklet().getAracTur());
        aracTurCombo.setModel(dlm);
        DefaultListModel dlm1 = new DefaultListModel();
        dlm1.addElement("Honda");
        dlm1.addElement("Peugeot");
        dlm1.addElement("Toyota");
        dlm1.addElement("Mazda");
        dlm1.addElement("Jeep");
        dlm1.addElement("Jaguar");
        modelList.setModel(dlm1);
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        adiTxt = new javax.swing.JTextField();
        soyTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        adiLbl = new javax.swing.JLabel();
        soyAdiLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        kayıtBtn = new javax.swing.JButton();
        borc = new javax.swing.JButton();
        hasarSorgu = new javax.swing.JButton();
        idAracTxt = new javax.swing.JTextField();
        aracTurCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aracIdTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        aracEkleBtn = new javax.swing.JButton();
        hasarEkleEkBtn = new javax.swing.JButton();
        kayitliMusteri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyTxtActionPerformed(evt);
            }
        });

        adiLbl.setText("Adı");

        soyAdiLbl.setText("Soyadı");

        idLbl.setText("Id");

        kayıtBtn.setText("Müşteri Kayıt");
        kayıtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtBtnActionPerformed(evt);
            }
        });

        borc.setText("Borç Sorgulama Ekranını Aç");
        borc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borcActionPerformed(evt);
            }
        });

        hasarSorgu.setText("Hasar Sorgulama Ekranını Aç");
        hasarSorgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasarSorguActionPerformed(evt);
            }
        });

        idAracTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idAracTxtKeyReleased(evt);
            }
        });

        aracTurCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aracTurCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aracTurComboİtemStateChanged(evt);
            }
        });
        aracTurCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                aracTurComboPropertyChange(evt);
            }
        });

        jLabel1.setText("Araç Tür");

        modelList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(modelList);

        jLabel2.setText("Araç Model");

        jLabel3.setText("Müşteri Id");

        jLabel4.setText("Bir araç id'si girin");

        aracIdTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aracIdTxtMousePressed(evt);
            }
        });
        aracIdTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                aracIdTxtPropertyChange(evt);
            }
        });
        aracIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aracIdTxtKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aracIdTxtKeyReleased(evt);
            }
        });

        aracEkleBtn.setText("Id'si girilen müşteriye araç ekle");
        aracEkleBtn.setToolTipText("id'si girilen müşteriye yeni bir araç kaydeder");
        aracEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracEkleBtnActionPerformed(evt);
            }
        });

        hasarEkleEkBtn.setText("Hasar Ekleme Ekranını Aç");
        hasarEkleEkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasarEkleEkBtnActionPerformed(evt);
            }
        });

        kayitliMusteri.setText("Kayıtlı Müşterileri Göster");
        kayitliMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitliMusteriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(aracTurCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(86, 86, 86))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idAracTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(aracEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(soyAdiLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(soyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aracIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hasarSorgu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(borc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasarEkleEkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(idLbl)
                        .addGap(18, 18, 18)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adiLbl)
                        .addGap(18, 18, 18)
                        .addComponent(adiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kayıtBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kayitliMusteri, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adiLbl)
                    .addComponent(borc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasarSorgu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soyAdiLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(hasarEkleEkBtn)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(kayıtBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kayitliMusteri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idAracTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aracTurCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(aracIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(aracEkleBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyTxtActionPerformed

    private void kayıtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtBtnActionPerformed
        Pattern p = Pattern.compile("[0-9]");
        Matcher m = p.matcher(adiTxt.getText());
        Matcher m1 = p.matcher(soyTxt.getText());
        
        Pattern p1 = Pattern.compile("[A-z]");
        Matcher m2 = p1.matcher(idTxt.getText());
        try {
            if (!adiTxt.getText().isEmpty() && !soyTxt.getText().isEmpty() && !m.find() && !m1.find() && !m2.find() && !idTxt.getText().isEmpty()) {
                
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("odev");
                EntityManager em = emf.createEntityManager();
                
                em.getTransaction().begin();
                Musteri musteri = new Musteri();
                musteri.setAdi(adiTxt.getText());
                musteri.setId(Integer.parseInt(idTxt.getText()));
                musteri.setSoyadi(soyTxt.getText());
                musteri.setBorc(0);
                
                em.persist(musteri);
                em.getTransaction().commit();
                em.close();
                emf.close();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Lütfen ad,soyad kısımlarına rakam ve id kısımına harf girmeyiniz ve eksiksiz doldurunuz", "Hata", JOptionPane.WARNING_MESSAGE);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Girilen id ile kayıtlı bir müşteri zaten var", "Hata", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_kayıtBtnActionPerformed

    private void aracTurComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_aracTurComboPropertyChange

    }//GEN-LAST:event_aracTurComboPropertyChange

    private void aracTurComboİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aracTurComboİtemStateChanged
        
        if (aracTurCombo.getSelectedItem().toString().equals("Araba")) {
            DefaultListModel dlm = new DefaultListModel();
            dlm.addElement("Honda");
            dlm.addElement("Peugeot");
            dlm.addElement("Toyota");
            dlm.addElement("Mazda");
            dlm.addElement("Jeep");
            dlm.addElement("Jaguar");
            modelList.setModel(dlm);
        } else if (aracTurCombo.getSelectedItem().toString().equals("Kamyon")) {
            DefaultListModel dlm = new DefaultListModel();
            dlm.addElement("Volvo");
            dlm.addElement("Mercedes");
            dlm.addElement("BMC");
            dlm.addElement("Ford");
            dlm.addElement("Renault");
            dlm.addElement("Scania");
            modelList.setModel(dlm);
        } else if (aracTurCombo.getSelectedItem().toString().equals("Motorsiklet")) {
            DefaultListModel dlm = new DefaultListModel();
            dlm.addElement("Yamaha");
            dlm.addElement("KTM");
            dlm.addElement("Harley-Davidson");
            dlm.addElement("BMW");
            dlm.addElement("Kawasaki");
            dlm.addElement("Honda");
            modelList.setModel(dlm);
        }
    }//GEN-LAST:event_aracTurComboİtemStateChanged

    private void aracEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracEkleBtnActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("odev");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        Query q = em.createQuery("select m from Musteri m where m.id= " + Integer.parseInt(idAracTxt.getText()));
        if (!q.getResultList().isEmpty()) {
            
            if (!idAracTxt.getText().isEmpty() && !aracIdTxt.getText().isEmpty() && !modelList.isSelectionEmpty()) {
                try {
                    if (aracTurCombo.getSelectedItem().toString().equals("Araba")) {
                        
                        Araba a = new Araba();
                        
                        a.setAracId(Integer.parseInt(aracIdTxt.getText()));
                        a.setModel(modelList.getSelectedValue().toString());
                        
                        a.setMusteriId(Integer.parseInt(idAracTxt.getText()));
                        
                        a.setTarih(d);
                        em.persist(a);
                        em.getTransaction().commit();
                        
                    } else if (aracTurCombo.getSelectedItem().toString().equals("Kamyon")) {
                        Kamyon a = new Kamyon();
                        a.setAracId(Integer.parseInt(aracIdTxt.getText()));
                        a.setModel(modelList.getSelectedValue());
                        a.setMusteriId(Integer.parseInt(idAracTxt.getText()));
                        a.setTarih(d);
                        em.persist(a);
                        em.getTransaction().commit();
                        
                    } else if (aracTurCombo.getSelectedItem().toString().equals("Motorsiklet")) {
                        Motorsiklet a = new Motorsiklet();
                        a.setAracId(Integer.parseInt(aracIdTxt.getText()));
                        a.setModel(modelList.getSelectedValue());
                        a.setMusteriId(Integer.parseInt(idAracTxt.getText()));
                        a.setTarih(d);
                        em.persist(a);
                        em.getTransaction().commit();
                    }
                } catch (javax.persistence.RollbackException e) {
                    JOptionPane.showMessageDialog(rootPane, "Girilen id ile bir araç mevcut", "Hata", JOptionPane.WARNING_MESSAGE);
                    
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Id alanları boş kalamaz ve bir araç modeli seçilmelidir", "Hata", JOptionPane.WARNING_MESSAGE);
                
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Girilen id ile eşleşen müşteri bulunamadı", "Hata", JOptionPane.WARNING_MESSAGE);
        }
        em.close();
        emf.close();
    }//GEN-LAST:event_aracEkleBtnActionPerformed

    private void aracIdTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_aracIdTxtPropertyChange

    }//GEN-LAST:event_aracIdTxtPropertyChange

    private void aracIdTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracIdTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aracIdTxtMousePressed

    private void aracIdTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aracIdTxtKeyTyped

    }//GEN-LAST:event_aracIdTxtKeyTyped

    private void aracIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aracIdTxtKeyReleased
        char[] a = aracIdTxt.getText().toCharArray();
        int sayac = 0;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < a.length; i++) {
            if (Character.isLetter(a[i])) {
                
                if (sayac == 0) {
                    sayac++;
                    JOptionPane.showMessageDialog(rootPane, "Id kısmına harf girilemez", "Hata", JOptionPane.WARNING_MESSAGE);
                    
                }
                
            } else {
                sb.append(a[i]);
            }
            aracIdTxt.setText(String.valueOf(sb));
        }
    }//GEN-LAST:event_aracIdTxtKeyReleased

    private void idAracTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idAracTxtKeyReleased
        char[] a = idAracTxt.getText().toCharArray();
        int sayac = 0;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < a.length; i++) {
            if (Character.isLetter(a[i])) {
                
                if (sayac == 0) {
                    sayac++;
                    JOptionPane.showMessageDialog(rootPane, "Id kısmına harf girilemez", "Hata", JOptionPane.WARNING_MESSAGE);
                    
                }
                
            } else {
                sb.append(a[i]);
            }
            idAracTxt.setText(String.valueOf(sb));
        }
    }//GEN-LAST:event_idAracTxtKeyReleased

    private void hasarEkleEkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasarEkleEkBtnActionPerformed
        hasarEkleme h = new hasarEkleme();
        h.setVisible(true);
        

    }//GEN-LAST:event_hasarEkleEkBtnActionPerformed

    private void hasarSorguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasarSorguActionPerformed
        hasarSorgu h = new hasarSorgu();
        h.setVisible(true);
        
    }//GEN-LAST:event_hasarSorguActionPerformed

    private void kayitliMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitliMusteriActionPerformed
        musteriler m = new musteriler();
        m.setVisible(true);
    }//GEN-LAST:event_kayitliMusteriActionPerformed

    private void borcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borcActionPerformed
     borc b = new borc();
     b.setVisible(true);
        
    }//GEN-LAST:event_borcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adiLbl;
    private javax.swing.JTextField adiTxt;
    private javax.swing.JButton aracEkleBtn;
    private javax.swing.JTextField aracIdTxt;
    private javax.swing.JComboBox<String> aracTurCombo;
    private javax.swing.JButton borc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton hasarEkleEkBtn;
    private javax.swing.JButton hasarSorgu;
    private javax.swing.JTextField idAracTxt;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kayitliMusteri;
    private javax.swing.JButton kayıtBtn;
    private javax.swing.JList<String> modelList;
    private javax.swing.JLabel soyAdiLbl;
    private javax.swing.JTextField soyTxt;
    // End of variables declaration//GEN-END:variables
}
